# syntax=docker/dockerfile:1
FROM golang:1.17-alpine

RUN apk update
RUN apk add --update bash && rm -rf /var/cache/apk/*

ENV TERM=xterm-256color
RUN mkdir /tacos
WORKDIR /tacos

COPY ./cmd /tacos/cmd
COPY ./pkg /tacos/pkg
COPY go.mod /tacos/

RUN go mod tidy
RUN go mod download

## Linux
#CGO_ENABLED=0 for cross-compiling as binary will be used outside of the container
RUN CGO_ENABLED=0 go build ./cmd/tacos  

ENTRYPOINT ["./tacos"]